server.port=8080
spring.application.name=productos
app.jwt.secret=a-string-secret-at-least-256-bits-long
app.jwt.expiration=86400000
app.security.username=admin
app.security.password=admin123

spring.autoconfigure.exclude=\
  org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
  org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
  org.springframework.boot.jdbc.autoconfigure.DataSourceTransactionManagerAutoConfiguration